### ISSUE TITLE
Moongose and Token error.

### ISSUE THREAD

**Issue by MayiVT** [mipcit1010/Vcodez#9]
[vcodez.xyz]: An error occurred while connecting mongoose. MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/connection.js:694:11)
    at /var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/index.js:351:10
    at /var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/var/www/list.mayivt.ml/Vcodez/node_modules/mongoose/lib/index.js:350:20)
    at module.exports (/var/www/list.mayivt.ml/Vcodez/src/database/connect.js:5:14)
    at Object.<anonymous> (/var/www/list.mayivt.ml/Vcodez/index.js:248:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
/var/www/list.mayivt.ml/Vcodez/node_modules/discord.js/src/client/Client.js:206
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/var/www/list.mayivt.ml/Vcodez/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/var/www/list.mayivt.ml/Vcodez/index.js:241:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'
}
[root@vps157 Vcodez]#

**Comment by mipcit1010** [comment]
We won't help with mongo errors that's not on our side, you did something wrong with your mongo. Ask in our code help channel on discord at https://vcodez.xyz/dc and we'll help you there,
Thanks, Masterious
